### ISSUE TITLE
Getting Contact Point Velocity (to Check for Slipping)

### ISSUE THREAD

**Issue by iamchoking** [railabatkaist/2023_ME491#2]
Hello, I am trying to detect if there is "foot slippage." But the two methods I used return different speeds

The folowing code is in the ```recordReward``` Function within the ```AnymalController_20190673.hpp``` (around ```line 160```)
(Stores values in ```wVelocity```)

Method 1: using ```anymal_->getPositionInBodyCoordinate``` and ```anymal_->getVelocity```
Method 2: using ```anymal_->getContactPointVel```

The comparison between two methods are done here:

The folowing code is in the ```recordReward``` Function within the ```AnymalController_20190673.hpp``` (around ```line 160```)
(Stores values in ```wVelocity```)
```
    for (auto &contact: anymal_->getContacts()) {
      if (footIndices_.find(contact.getlocalBodyIndex()) != footIndices_.end()) { // is a foot contact
        anymal_->getPositionInBodyCoordinate(contact.getlocalBodyIndex(),contact.getPosition(),bContact);
        anymal_->getVelocity(contact.getlocalBodyIndex(),bContact,contactVel1);
        anymal_->getContactPointVel(contact.getIndexInObjectContactList(),contactVel2);
        std::cout << "Vel1 : " << contactVel1 << std::endl;
        std::cout << "Vel2 : " << contactVel2 << std::endl;
      }
    }
```

The output are "similar" in magnitude, but have different values:
```
Vel2 : -1.1467e-08 
1.636e-08 
0.000683059 

Vel1 : -0.00200529 
-0.000234563 
0.00256339 

Vel2 : -1.05179e-16 
2.14863e-16 
0.00211952 

Vel1 : 0.000538365 
0.0024712 
0.00661803 

Vel2 : 1.79501e-09 
1.16415e-09 
0.000421839 

Vel1 : -0.00104689 
-3.02906e-05 
0.000959762 

Vel2 : -4.63908e-09 
1.72354e-08 
0.000681108 
```
Can I get help on which one is the correct method of detecting the right foot contact point velocity of the robot?

**Comment by jhwangbo** [comment]
``anymal_->getContactPointVel`` returns the contact velocity in the contact frame. It's z-axis is normal to the tagent plane.
